---
- hosts: 172.31.24.84
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: copy static files into nodes
    copy:
        src: mytestfile
        dest: /home/ubuntu/staticfile

  - name: install webserver on nodes
    apt:
      name: apache2
      state: present

  - name: copy dynamicfiles into nodes 
    template: 
        src: myindex.j2
        dest: /var/www/html/index.html

  - name: download files into nodes  
    get_url:
     url: https://get.jenkins.io/war-stable/2.375.1/jenkins.war
     dest: /home/ubuntu/jenkins.war
    force_basic_auth: yes   