---
- hosts: 172.31.24.84
  become: yes
  tasks: 
  - name: install git
    apt: 
      name: git
      state: present
    tags: mygit
  - name: inatall tree
    apt:
      name: tree
      state: present
    tags: mytree  

  - name: install wget
    apt:
      name: wget
      state: present
    tags: mywget  
